### ISSUE TITLE
Execute permission on handler script

### ISSUE THREAD

**Issue by whitehat101** [EnigmaBridge/certbot-external-auth#1]
I received an obscure error from the following:

```
$ certbot --staging \
         --text --agree-tos --email you@example.com \
         --expand --renew-by-default \
         --configurator certbot-external-auth:out \
         --certbot-external-auth:out-public-ip-logging-ok \
         -d "example.com" \
         --preferred-challenges dns \
         --certbot-external-auth:out-handler /vagrant/handlers/dns.sh \
         certonly
``` 
```
Encountered exception during recovery
[Errno 13] Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 279, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/dist-packages/certbot_external_auth/plugin.py", line 289, in cleanup
    if self._is_classic_handler_mode() and self._call_handler("pre-cleanup") is None:
  File "/usr/local/lib/python2.7/dist-packages/certbot_external_auth/plugin.py", line 666, in _call_handler
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
An unexpected error occurred:
OSError: [Errno 13] Permission denied
Please see the logfiles in /var/log/letsencrypt for more details.
{"cmd": "report", "messages": []}
```

Initially I assumed it was demanding root/sudo, but that wasn't the case. It was actually complaining that there was no +x on the handler script. Can we get a more descriptive error?

The error message for a missing handler file could similarly be improved.

**Comment by ph4r05** [comment]
Thanks for suggestions! I will submit a new version with the fix

**Comment by ph4r05** [comment]
Error messages were refactored and improved.

Error if handler is not executable:

```
Handler script invocation failed with an exception. 
 - Script: ./dh.sh deploy_challenge bristol3.pki.enigmabridge.com _QLSFTRw6qbQaN7gTglBYZuU1L7KAP-bXB_41CAnAvU 667drNmQL3vX6bu8YZlgy0wKNBlCny8yrjF1lSaUndc
 - Exception: [Errno 13] Permission denied
Handler script ./dh.sh does not have the executable permission set so it cannot be executed. 
 - Try running: chmod +x "/home/ec2-user/certbot-external-auth/dh.sh" 
```

If it does not exist:

```
Handler script file `./dh2.sh` not found. Absolute path: /home/ec2-user/certbot-external-auth/dh2.sh
```

If it is not a file (nor symlink to file)

```
Handler script file `.` not found. Absolute path: /home/ec2-user/certbot-external-auth
Handler script `.` is not a file
```
