### ISSUE TITLE
ContextualVersionConflict

### ISSUE THREAD

**Issue by dancvrcek** [EnigmaBridge/certbot-external-auth#4]
I have launched a fresh EC2 on Amazon - the Amazon Linux version. 

sudo su
yum groupinstall 'Development Tools'
yum install gcc libffi-devel python-devel openssl-devel
pip install certbot
pip install certbot-external-auth
exit
certbot     --text --agree-tos --email you@example.com \
    --expand --renew-by-default     --configurator certbot-external-auth:out    \
    --certbot-external-auth:out-public-ip-logging-ok\
     -d "bristol3.pki.enigmabridge.com"     --preferred-challenges dns     certonly

... and I got this error

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 858, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 183, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 34, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2311, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2328, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'), set(['mock']))

**Comment by dancvrcek** [comment]
ah, this was needed

sudo pip install --upgrade six
