### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by Torxed** [EnigmaBridge/certbot-external-auth#6]
```
Encountered exception during recovery
module 'types' has no attribute 'StringTypes'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot-0.15.0-py3.6.egg/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib/python3.6/site-packages/certbot_external_auth-0.0.8-py3.6.egg/certbot_external_auth/plugin.py", line 204, in perform
    responses.append(mapping[achall.typ](achall))
  File "/usr/lib/python3.6/site-packages/certbot_external_auth-0.0.8-py3.6.egg/certbot_external_auth/plugin.py", line 477, in _perform_dns01_challenge
    self._json_out_and_wait(json_data)
  File "/usr/lib/python3.6/site-packages/certbot_external_auth-0.0.8-py3.6.egg/certbot_external_auth/plugin.py", line 781, in _json_out_and_wait
    self._json_out(data, True)
  File "/usr/lib/python3.6/site-packages/certbot_external_auth-0.0.8-py3.6.egg/certbot_external_auth/plugin.py", line 773, in _json_out
    json_str = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

Most likely because how Python2 and Python3 differs?

**Comment by jefft** [comment]
I hit another variant of this error trying to run certbot in a Python 3 venv:
````
Encountered exception during recovery
module 'types' has no attribute 'StringTypes'
Traceback (most recent call last):
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 204, in perform
    responses.append(mapping[achall.typ](achall))
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 480, in _perform_dns01_challenge
    self._json_out(json_data, True)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 773, in _json_out
    json_str = json.dumps(data)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'y8HTM3DDZjMXP4r9iEx8ai9c3p7E3yPATHubGo50QwI' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 296, in cleanup
    cur_record = self._get_cleanup_json(achall)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 331, in _get_cleanup_json
    cur_record[FIELD_VALIDATION] = validation if isinstance(validation, types.StringTypes) else ''
AttributeError: module 'types' has no attribute 'StringTypes'
An unexpected error occurred:
TypeError: b'y8HTM3DDZjMXP4r9iEx8ai9c3p7E3yPATHubGo50QwI' is not JSON serializable
Please see the logfiles in /var/log/letsencrypt for more details.
{"cmd": "report", "messages": []}
````
After switching to @Torxed's branch incorporating #7, the error changes slightly:
````
Encountered exception during recovery
module 'types' has no attribute 'StringTypes'
Traceback (most recent call last):
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 205, in perform
    responses.append(mapping[achall.typ](achall))
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 484, in _perform_dns01_challenge
    if self._call_handler("perform", **(self._get_json_to_kwargs(json_data))) is None:
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 371, in _get_json_to_kwargs
    if isinstance(val, types.FloatType):
AttributeError: module 'types' has no attribute 'FloatType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 297, in cleanup
    cur_record = self._get_cleanup_json(achall)
  File "/home/jturner/le/venv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 332, in _get_cleanup_json
    cur_record[FIELD_VALIDATION] = validation if isinstance(validation, types.StringTypes) else ''
AttributeError: module 'types' has no attribute 'StringTypes'
An unexpected error occurred:
AttributeError: module 'types' has no attribute 'FloatType'
Please see the logfiles in /var/log/letsencrypt for more details.
{"cmd": "report", "messages": []}
````
I've attempted to create a reproducible test case, and found I could trigger the symptoms if the auth handler script doesn't exist:
````
Python 3.5.3
python3 -m venv testextauth
. testextauth/bin/activate
export MYEMAIL=...    # Set something valid
export DOMAIN=...      # Set something valid
certbot certonly --text --agree-tos --no-eff-email --email $MYEMAIL --expand --preferred-challenges dns -a certbot-external-auth:out --certbot-external-auth:out-public-ip-logging-ok --certbot-external-auth:out-handler nonexistent.sh -d test.$MYDOMAIN --config-dir letencrypt/config  --work-dir=letsencrypt/work --logs-dir=letsencrypt/logs
````
The error is:
````
Saving debug log to /tmp/letsencrypt/logs/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for test.redradishtech.com
Handler script file `nonexistent.sh` not found. Absolute path: /tmp/nonexistent.sh
Cleaning up challenges
Encountered exception during recovery
module 'types' has no attribute 'StringTypes'
Traceback (most recent call last):
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 201, in perform
    raise errors.PluginError("Error in calling the handler to do the pre-perform (challenge) stage")
certbot.errors.PluginError: Error in calling the handler to do the pre-perform (challenge) stage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 296, in cleanup
    cur_record = self._get_cleanup_json(achall)
  File "/tmp/testextauth/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 331, in _get_cleanup_json
    cur_record[FIELD_VALIDATION] = validation if isinstance(validation, types.StringTypes) else ''
AttributeError: module 'types' has no attribute 'StringTypes'
Error in calling the handler to do the pre-perform (challenge) stage
{"cmd": "report", "messages": []}

````
After upgrading to @Torxed branch:
````
pip install --upgrade git+https://github.com/Torxed/certbot-external-auth
````
and rerunning the test:
````
Saving debug log to /tmp/letsencrypt/logs/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for test.redradishtech.com
Handler script file `nonexistent.sh` not found. Absolute path: /tmp/nonexistent.sh
Cleaning up challenges
Encountered exception during recovery
module 'types' has no attribute 'StringTypes'
Traceback (most recent call last):
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 202, in perform
    raise errors.PluginError("Error in calling the handler to do the pre-perform (challenge) stage")
certbot.errors.PluginError: Error in calling the handler to do the pre-perform (challenge) stage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 297, in cleanup
    cur_record = self._get_cleanup_json(achall)
  File "/tmp/testvenv/lib/python3.5/site-packages/certbot_external_auth/plugin.py", line 332, in _get_cleanup_json
    cur_record[FIELD_VALIDATION] = validation if isinstance(validation, types.StringTypes) else ''
AttributeError: module 'types' has no attribute 'StringTypes'
Error in calling the handler to do the pre-perform (challenge) stage
{"cmd": "report", "messages": []}
````

**Comment by ph4r05** [comment]
Thanks! I will take a look, this should be easy to solve

**Comment by ph4r05** [comment]
Hi folks, 
thanks you all to your contributions.

Tested py2.7.14, py3.6.3, seems to work. 

Closing.

**Comment by Torxed** [comment]
@ph4r05 cool, glad it works :D Will pull the latest master and try tonight!

**Comment by ph4r05** [comment]
@Torxed pls let me know if there is any problem with it, I am available for this again.

Sorry guys for the long delays on this, I've been totally busy few months.

**Comment by Torxed** [comment]
@ph4r05 No worries, I'll let you know asap. And don't sweat it, we're doing this because we love it - not because we have to :)
